CREATE TABLE video
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name    VARCHAR(255)                            NOT NULL,
    metadata_id  BIGINT,
    statistic_id BIGINT,
    deleted      BOOLEAN,
    CONSTRAINT pk_video PRIMARY KEY (id)
);

CREATE TABLE video_metadata
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    video_id     BIGINT,
    title        VARCHAR(255),
    synopsis     VARCHAR(255),
    author       VARCHAR(255),
    release_year INTEGER,
    genre        VARCHAR(255),
    running_time BIGINT,
    CONSTRAINT pk_videometadata PRIMARY KEY (id)
);

CREATE TABLE video_statistic
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    video_id    BIGINT,
    impressions BIGINT,
    views       BIGINT,
    CONSTRAINT pk_videostatistic PRIMARY KEY (id)
);

ALTER TABLE video
    ADD CONSTRAINT uc_video_metadata UNIQUE (metadata_id);

ALTER TABLE video
    ADD CONSTRAINT uc_video_statistic UNIQUE (statistic_id);

ALTER TABLE video_metadata
    ADD CONSTRAINT uc_videometadata_video UNIQUE (video_id);

ALTER TABLE video_statistic
    ADD CONSTRAINT uc_videostatistic_video UNIQUE (video_id);

ALTER TABLE video_metadata
    ADD CONSTRAINT FK_VIDEOMETADATA_ON_VIDEO FOREIGN KEY (video_id) REFERENCES video (id);

ALTER TABLE video_statistic
    ADD CONSTRAINT FK_VIDEOSTATISTIC_ON_VIDEO FOREIGN KEY (video_id) REFERENCES video (id);

ALTER TABLE video
    ADD CONSTRAINT FK_VIDEO_ON_METADATA FOREIGN KEY (metadata_id) REFERENCES video_metadata (id);

ALTER TABLE video
    ADD CONSTRAINT FK_VIDEO_ON_STATISTIC FOREIGN KEY (statistic_id) REFERENCES video_statistic (id);